# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.sourcesDirectory)'
    includeRootFolder: false
- task: PublishBuildArtifacts@1

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Free Trial (d9b577eb-8a8e-4c20-ad71-e43d687f3d9d)'
    appType: 'webAppLinux'
    WebAppName: 'PranavTestApp'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'